---
{{cookiecutter.app_type}}_servers: {{cookiecutter.lname}}_servers
cops_{{cookiecutter.app_type}}_name: "{{cookiecutter.lname}}"
cops_{{cookiecutter.app_type}}_tld_domain: "{{cookiecutter.tld_domain}}"
cops_{{cookiecutter.app_type}}_mail_domain: "{{ cookiecutter.mail_domain }}"
cops_{{cookiecutter.app_type}}_docker_image: "{{cookiecutter.docker_image}}"
cops_{{cookiecutter.app_type}}_gitref: "{{'{{'}}lookup('env', 'CI_COMMIT_TAG_NAME') or lookup('env', 'CI_COMMIT_REF_NAME') or 'latest'}}"
cops_{{cookiecutter.app_type}}_docker_tag: "{{'{{'}}cops_{{cookiecutter.app_type}}_gitref.replace('master', 'latest')}}"
{% if 'post' in cookiecutter.db_mode -%}
cops_{{cookiecutter.app_type}}_mysql_startup_timeout: 45s
{%- endif %}
cops_{{cookiecutter.app_type}}_docker_env_extra: |-
  # db
  MYSQL_STARTUP_TIMEOUT={{'{{'}}cops_{{cookiecutter.app_type}}_mysql_startup_timeout}}
cops_wordpress_restarted_services: "{{'{{'}}cops_wordpress_restarted_services_default.replace(' wordpress', ' wordpress')}}"
cops_wordpress_db_prefix: "wp_{{cookiecutter.lname}}"
cops_wordpress_db_user: "wp{{cookiecutter.lname}}"
